# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: publication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11publication.proto\"0\n\x04\x44\x61te\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12\r\n\x05month\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\t\"\x87\x01\n\x0bPublication\x12\x11\n\tstationId\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x12\x0c\n\x04rain\x18\x04 \x01(\x02\x12\x0c\n\x04wind\x18\x05 \x01(\x02\x12\x11\n\tdirection\x18\x06 \x01(\t\x12\x13\n\x04\x64\x61te\x18\x07 \x01(\x0b\x32\x05.Dateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'publication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DATE']._serialized_start=21
  _globals['_DATE']._serialized_end=69
  _globals['_PUBLICATION']._serialized_start=72
  _globals['_PUBLICATION']._serialized_end=207
# @@protoc_insertion_point(module_scope)
